### ISSUE TITLE
Build Spark 2014 semantics with Coq 8.8

### ISSUE THREAD

**Issue by robblanco** [AdaCore/sparkformal#2]
Coq 8.8 fails to build the Spark 2014 semantics sub-project due to its inability to infer a decreasing argument in a non-recursive function with let bindings. This has been described and reported as an issue here: coq/coq#8226.

A workaround that permits the build to go through is here: robblanco/sparkformal@b5654586606c7f6b9947de8518add7fdaa2d904a.

**Comment by yannickmoy** [comment]
Thanks for reporting that issue. I have assigned it to Pierre Courtieu (Matafou) for updating the semantics.

**Comment by robblanco** [comment]
No problem. The issue should go away when the bug gets fixed in Coq. I can create a PR for the workaround if @Matafou thinks it makes sense. If the inlining of the `let` is to be temporary, the original, unfixed definition could be retained protected by `Fail` so that one is forced to undo the hack when the problem in Coq is fixed.

**Comment by Matafou** [comment]
@robblanco please do.
I don't know if this will be temporary yet.

**Comment by yannickmoy** [comment]
fixed by @Matafou in PR#4 by porting to Coq 8.12
